Add support for MQTT LWT
ClearBlade/ClearBlade-Python-SDK pull request #30
Opened 2024-03-06 23:21 UTC by savfaire

2024-03-06 23:50 UTC, sky-sharma requested changes

2024-03-06 23:50 UTC, sky-sharma commented on setup.py
>      download_url='https://github.com/ClearBlade/ClearBlade-Python-SDK/archive/v2.4.4.tar.gz',
@savfaire unfortunately in this old file we were used to changing the version in two places. Where you did and before the .tar.gz. Maybe this is a good time to make this smarter and use the version to build the path to the tar.gz. Can you go ahead?

2024-03-07 00:07 UTC, savfaire commented
I’ll look into it.

On Mar 6, 2024, at 5:50 PM, akash-sharma-ext-clearblade ***@***.***> wrote:

﻿

@sky-sharma requested changes on this pull request.

________________________________

In setup.py<https://github.com/ClearBlade/ClearBlade-Python-SDK/pull/30#discussion_r1515296101>:

> @@ -4,7 +4,7 @@
     name='clearblade',
     packages=['clearblade'],
     install_requires=['requests', 'paho-mqtt>=1.3.0'],
-    version='2.4.4',
+    version='2.4.5',
     description='A Python SDK for interacting with the ClearBlade Platform.',
     url='https://github.com/ClearBlade/ClearBlade-Python-SDK',
     download_url='https://github.com/ClearBlade/ClearBlade-Python-SDK/archive/v2.4.4.tar.gz',


@savfaire<https://github.com/savfaire> unfortunately in this old file we were used to changing the version in two places. Where you did and before the .tar.gz. Maybe this is a good time to make this smarter and use the version to build the path to the tar.gz. Can you go ahead?

—
Reply to this email directly, view it on GitHub<https://github.com/ClearBlade/ClearBlade-Python-SDK/pull/30#pullrequestreview-1921050297>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABFUBRQ2Y5MU5G2J233AQ23YW6TUNAVCNFSM6AAAAABEJ6Q77WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMRRGA2TAMRZG4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-03-07 21:38 UTC, sky-sharma approved these changes

2024-03-07 21:39 UTC, merged